providers:
  - name: github
    github:
      token: ${GITHUB_TOKEN}
  - name: gitlab
    gitlab:
      token: ${GITLAB_TOKEN}
      url: https://git.sos.ethz.ch
repos:
  - name: kubernetes
    origin:
      provider: gitlab
      name: pkgs/k8s/kubernetes
    mirrors:
      - provider: github
        name: vsk8s/kubernetes
  - name: calico
    origin:
      provider: gitlab
      name: pkgs/k8s/calico
    mirrors:
      - provider: github
        name: vsk8s/calico
  - name: cni-plugins
    origin:
      provider: gitlab
      name: pkgs/k8s/cni-plugins
    mirrors:
      - provider: github
        name: vsk8s/plugins
  - name: etcd
    origin:
      provider: gitlab
      name: pkgs/k8s/etcd
    mirrors:
      - provider: github
        name: vsk8s/etcd
  - name: gitsync
    origin:
      provider: github
      name: SOSETH/gitsync
    mirrors:
      - provider: gitlab
        name: isg/gitsync
  - name: grafana-agent
    origin:
      provider: github
      name: SOSETH/grafana-agent
    mirrors:
      - provider: gitlab
        name: ansibleroles/grafana-agent
  - name: grafana
    origin:
      provider: github
      name: SOSETH/grafana
    mirrors:
      - provider: gitlab
        name: ansibleroles/grafana
  - name: awx
    origin:
      provider: github
      name: SOSETH/awx
    mirrors:
      - provider: gitlab
        name: ansibleroles/awx
  - name: k3s
    origin:
      provider: github
      name: SOSETH/k3s
    mirrors:
      - provider: gitlab
        name: ansibleroles/k3s
  - name: local-ca
    origin:
      provider: github
      name: SOSETH/local-ca
    mirrors:
      - provider: gitlab
        name: ansibleroles/local-ca
  # vault is archived
  # vault-agent is archived
  - name: vaultwarden
    origin:
      provider: github
      name: SOSETH/vaultwarden
    mirrors:
      - provider: gitlab
        name: ansibleroles/vaultwarden
  - name: debian-ci-base
    origin:
      provider: github
      name: SOSETH/debian-ci-base
    mirrors:
      - provider: gitlab
        name: isg/debian-ci-base
  - name: ssh
    origin:
      provider: github
      name: SOSETH/ssh
    mirrors:
      - provider: gitlab
        name: ansibleroles/ssh
  - name: mailserver
    origin:
      provider: github
      name: SOSETH/mailserver
    mirrors:
      - provider: gitlab
        name: ansibleroles/mailserver
  - name: regional
    origin:
      provider: github
      name: SOSETH/regional
    mirrors:
      - provider: gitlab
        name: ansibleroles/regional
  - name: gitlab-runner
    origin:
      provider: github
      name: SOSETH/gitlab-runner
    mirrors:
      - provider: gitlab
        name: ansibleroles/gitlab-runner
  # vault-proxy is archived
  - name: network
    origin:
      provider: github
      name: SOSETH/network
    mirrors:
      - provider: gitlab
        name: ansibleroles/network
  - name: time
    origin:
      provider: github
      name: SOSETH/time
    mirrors:
      - provider: gitlab
        name: ansibleroles/time
  - name: apt
    origin:
      provider: github
      name: SOSETH/apt
    mirrors:
      - provider: gitlab
        name: ansibleroles/apt
  # monitoring-base is archived
  - name: mailclient
    origin:
      provider: github
      name: SOSETH/mailclient
    mirrors:
      - provider: gitlab
        name: ansibleroles/mailclient
  - name: router
    origin:
      provider: github
      name: SOSETH/router
    mirrors:
      - provider: gitlab
        name: ansibleroles/router
  - name: kerberos
    origin:
      provider: github
      name: SOSETH/kerberos
    mirrors:
      - provider: gitlab
        name: ansibleroles/kerberos
  - name: letsencrypt
    origin:
      provider: github
      name: SOSETH/letsencrypt
    mirrors:
      - provider: gitlab
        name: ansibleroles/letsencrypt
  # consul is archived
  - name: victoriametrics
    origin:
      provider: github
      name: SOSETH/victoriametrics
    mirrors:
      - provider: gitlab
        name: ansibleroles/victoriametrics
  # terraform-vault-ca is archived
  - name: nginx
    origin:
      provider: github
      name: SOSETH/nginx
    mirrors:
      - provider: gitlab
        name: ansibleroles/nginx
  - name: dns-resolver
    origin:
      provider: github
      name: SOSETH/dns-resolver
    mirrors:
      - provider: gitlab
        name: ansibleroles/dns-resolver
  # monitoring-server is archived
  # check_iostat is archived
  - name: docker
    origin:
      provider: github
      name: SOSETH/docker
    mirrors:
      - provider: gitlab
        name: ansibleroles/docker
  - name: apache
    origin:
      provider: github
      name: SOSETH/apache
    mirrors:
      - provider: gitlab
        name: ansibleroles/apache
  - name: haproxy
    origin:
      provider: github
      name: SOSETH/haproxy
    mirrors:
      - provider: gitlab
        name: ansibleroles/haproxy
  - name: ipmi
    origin:
      provider: github
      name: SOSETH/ipmi
    mirrors:
      - provider: gitlab
        name: ansibleroles/ipmi
  - name: ocserv
    origin:
      provider: github
      name: SOSETH/ocserv
    mirrors:
      - provider: gitlab
        name: ansibleroles/ocserv
  # check_sas_smart is archived
  # check_smartvalues is archived
  # check_raid is archived
  # check_mem is archived
  - name: sh
    origin:
      provider: github
      name: SOSETH/sh
    mirrors:
      - provider: gitlab
        name: ansibleroles/sh
  #tcpdup is archived
  - name: mariadb
    origin:
      provider: github
      name: SOSETH/mariadb
    mirrors:
      - provider: gitlab
        name: ansibleroles/mariadb
  # mariadb-ha is archived
  - name: programs
    origin:
      provider: github
      name: SOSETH/programs
    mirrors:
      - provider: gitlab
        name: ansibleroles/programs
  - name: motd
    origin:
      provider: github
      name: SOSETH/motd
    mirrors:
      - provider: gitlab
        name: ansibleroles/motd
  - name: apt-dater-host
    origin:
      provider: github
      name: SOSETH/apt-dater-host
    mirrors:
      - provider: gitlab
        name: ansibleroles/apt-dater-host
  - name: mollyguard
    origin:
      provider: github
      name: SOSETH/mollyguard
    mirrors:
      - provider: gitlab
        name: ansibleroles/mollyguard
  # sos-monitoring-tools does not have a mirror
  # monitoring-client is archived
  # monitoring-proxy is archived
  # graphite_exporter has no mirror
  # check_ipmi_sensor_v3 is archived
  # check_ib is archived
  - name: aptly
    origin:
      provider: github
      name: SOSETH/aptly
    mirrors:
      - provider: gitlab
        name: ansibleroles/aptly
  # snmp_exporter has no mirror
  - name: tmux
    origin:
      provider: github
      name: SOSETH/tmux
    mirrors:
      - provider: gitlab
        name: ansibleroles/tmux
  - name: python-ci-base
    origin:
      provider: github
      name: SOSETH/python-ci-base
    mirrors:
      - provider: gitlab
        name: isg/python-ci-base
  # check_lsi_raid is archived
  # ceph_exporter is archived
  # check_ceph_dash is archived
  # check_power is archived
  # check-ceph is archived
  # check_snmp_int is archived
  # check_lm_sensors is archived
  # check_apcupsd is archived
  # send-pmg-report is archived
  # ceph-dash has no mirror
